language: scala
jdk:
  - openjdk8
  - openjdk11
sudo: false
scala:
  - 2.11.12
  - 2.12.8
script:
  - >
    sbt ++$TRAVIS_SCALA_VERSION
    scalafmtCheckAll capturl-akka-http/scalafmtCheckAll
    headerCheck test:headerCheck
    capturl-akka-http/headerCheck capturl-akka-http/test:headerCheck
    test capturl-akka-http/test
  - >
    if [[ $TRAVIS_SCALA_VERSION == 2.12.* ]]; then sbt ++$TRAVIS_SCALA_VERSION
    capturl-contextual/scalafmtCheckAll
    capturl-contextual/headerCheck capturl-contextual/test:headerCheck
    capturl-contextual/test; fi